#!/bin/bash

# Setup git hooks
# This script sets up the pre-commit hook

set -e

GIT_DIR=$(git rev-parse --git-dir)
HOOKS_DIR="$GIT_DIR/hooks"
PRE_COMMIT_HOOK="$HOOKS_DIR/pre-commit"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "Setting up git hooks..."

# Create hooks directory if it doesn't exist
mkdir -p "$HOOKS_DIR"

# Create pre-commit hook
cat > "$PRE_COMMIT_HOOK" << 'HOOK_EOF'
#!/bin/bash
# Pre-commit hook - generated by setup-git-hooks.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
exec "$SCRIPT_DIR/scripts/pre-commit-hook.sh"
HOOK_EOF

chmod +x "$PRE_COMMIT_HOOK"

echo "✓ Pre-commit hook installed at $PRE_COMMIT_HOOK"
echo ""
echo "The hook will:"
echo "  1. Detect if resume files are being committed"
echo "  2. Generate resume PDF automatically"
echo "  3. Add the PDF to the same commit"
echo ""
echo "To skip the hook, use: git commit --no-verify"
